name: Code Verification Workflow

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read  # least privilege for this workflow
  actions: none   # disable unnecessary permissions

jobs:
  verify-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run linting (flake8)
        run: |
          pip install flake8
          flake8 .

      - name: Run tests
        run: |
          # Replace with your test command, e.g. pytest
          echo "No tests defined yet"

      - name: Security scan with CodeQL
        uses: github/codeql-action/analyze@v2
        with:
          category: "security"

      - name: Upload workflow logs on failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: workflow-logs
          path: ./logs

      - name: Notify on success
        if: success()
        run: echo "Code verification succeeded."
